services:
  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.0}
    ports:
      - "3100:3100"
    volumes:
     - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v3.3.0}
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
   image: grafana/grafana:${GRAFANA_VERSION:-11.6.1}
   environment:
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_BASIC_ENABLED=false
   ports:
     - 3000:3000/tcp
   entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

  alloy:
   image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.8.2}
   ports:
     - 12345:12345
     - 4317:4317
     - 4318:4318
   volumes:
     - ./config.alloy:/etc/alloy/config.alloy
     - /var/run/docker.sock:/var/run/docker.sock
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  pyroscope:
    image: grafana/pyroscope:main-88b2152
    ports:
    - 4040:4040
    depends_on:
      - grafana

  # influxdb3-core:
  #   image: influxdb:3-core
  #   ports:
  #     - 8181:8181
  #   command:
  #     - influxdb3
  #     - serve
  #     - --node-id=node0
  #     - --object-store=file
  #     - --data-dir=/var/lib/influxdb3/data
  #     - --plugin-dir=/var/lib/influxdb3/plugins
  #   volumes:
  #     - type: bind
  #       # Path to store data on your host system
  #       source: ~/.influxdb3/data
  #       # Path to store data in the container
  #       target: /var/lib/influxdb3/data
  #     - type: bind
  #       # Path to store plugins on your host system
  #       source: ~/.influxdb3/plugins
  #       # Path to store plugins in the container
  #       target: /var/lib/influxdb3/plugins

#   influxdb3-explorer:
#     image: influxdata/influxdb3-ui:1.0.0
#     container_name: influxdb3-explorer
#     ports:
#       - "8888:80"
#       - "8889:8888"
#     command: ["--mode=admin"]
#     restart: unless-stopped

# volumes:
#   alloy-data: